export const galleryNames = [
  { main: "austria_2021" },
  { main: "jeseniky_2021" },
  { main: "slovakia_2020" },
  { main: "slaniska_2020" },
  { main: "perm_plot" },
  { main: "mohelno_2019" },
  { main: "macedonia_2019" },
  { main: "corsica_2018" },
  { main: "romania_2017" },
  { main: "albania_2016" },
  { main: "serbia_2015" },
  { main: "poland_2014" },
  { main: "sardinia_2013" },
  { main: "swiss_2012" },
  { main: "turkey_2011" },
  { main: "france_2009" },
  { main: "ukraine_2008" },
  { main: "italy_2007" },
];

export const galleryNamesCz = [
  "2021 Rakousko",
  "2021 Jeseníky",
  "2020 Slovensko",
  "2020 Dolní Dunajovice, slaniska",
  "2019 Bohunice, pokusné plochy",
  "2019 Mohelno",
  "2019 Severní Makedonie",
  "2018 Korsika",
  "2017 Rumunsko",
  "2016 Albánie + Černá Hora",
  "2015 Srbsko",
  "2014 Polsko",
  "2013 Sardinie",
  "2012 Švýcarsko",
  "2011 Turecko",
  "2009 Francie",
  "2008 Ukrajina",
  "2007 Itálie",
];
export const galleryNamesEn = [
  "2021 Austria",
  "2021 Jeseníky mountains",
  "2020 Slovakia",
  "2020 Dolní Dunajovice",
  "2019 Bohunice, permanent plots",
  "2019 Mohelno", 
  "2019 North Macedonia",
  "2018 Corsica",
  "2017 Romania",
  "2016 Albania + Montenegro",
  "2015 Serbia",
  "2014 Poland",
  "2013 Sardinia",
  "2012 Switzerland",
  "2011 Turkey",
  "2009 France",
  "2008 Ukraine",
  "2007 Italy"
];

export const galleryLabelsCz = {
  austria_2021: ["", "Neusiedler See", "Hordeum jubatum", "Erigeron podolicus", "Neusiedler See", "Neusiedler See", "Allium angulosum", "Neusiedler See", "Neusiedl am See, Kalvarienberg", "Neusiedl am See, Kalvarienberg", "Koralpen", "Gentiana pannonica", "Koralpen", "Koralpen", "Dianthus superbus", "Koralpen", "Koralpen, Grosser Speikkogel", "", "Faaker See", "Faaker See", "Faaker See", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Dryas octopetala", "Lienzer Dolomiten, Lasersee", "Pasterze", "Pasterze", "Cirsium spinosissimum", "Marmota marmota", "Leontopodium alpinum", "Sempervivum arachnoideum", "Lomatogonium carinthiacum", "", "Warscheneck", "Wienerwald, Pinus nigra"],
  jeseniky_2021: ["Velký kotel", "", "", "Trollius altissimus", "", "", "", "Plantago atrata", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Vysoká hole", "", "", "", "Listera cordata", "", "", "", "Salix herbacea", "", "Poa riphaea", "", "", "", "", ],
  slovakia_2020: ["","Terchová-Diery", "Corthusa matthioli", "Terchová-Diery","", "Cirsium eriophorum", "Terchová-Tiesňavy", "Ranunculus alpestris", "V. Fatra-Tlstá", "Gentianella fatrae", "V. Fatra-Tlstá", "Lappula squarrosa", "Velká Fatra", "Velká Fatra", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Rhodiola rosea", "Gentiana asclepiadea", "Adenostyles alliariae", "Malá Studená dolina", "Spišské pleso", "Spišské pleso","Salix herbacea", "Téryho chata", "kemp Tatranská Štrba", "kemp Tatranská Štrba", "kemp Tatranská Štrba; výstavka","Primovské skaly", "Primovské skaly", "Galatella linosyris", "Eresus kollari", "Sivá brada", "Sivá brada", "Sivá brada", "Sivá brada", "Ostrá hora", "Ostrá hora", "Aconitum anthora", "Velké Biele pleso", "Kopské sedlo", "Kopské sedlo", "Kopské sedlo", "Adenophora liliifolia", "Rosa pendulina", "Rosa spinosissima", "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Geastrum sp.", "Prielom Hornádu" , "Stratenský kaňon", "Hnilecká jelšina", "Succisa pratensis + Polygonia c-album", "Ligularia sibirica", "Hnilecká jelšina", "Hnilecká jelšina", "CoronaBus :-)"],
  slaniska_2020: ["Trifolium fragiferum", "Lotus tenuis", "Sedlec", "", "", "","Slanisko u Nesytu", "Slanisko u Nesytu", "Slanisko u Nesytu", "Slanisko u Nesytu", "Dolní Dunajovice", "Dolní Dunajovice", "Zwingendorf", "Zwingendorf", "Zwingendorf", "Zwingendorf", "Zwingendorf; Althaea officinalis", "Zwingendorf", "Zwingendorf", "Nový Přerov", "Nový Přerov", "Nový Přerov", "Nový Přerov", "Starovický rybník", "Trkmanec-Rybníčky", "Trkmanec-Rybníčky", "Trkmanec-Rybníčky", "Dobré Pole", "Novosedly", "", "", "", "Dunajovické kopce; Crambe tataria", "Dunajovické kopce","Dunajovické kopce; Linum hirsutum", "Dunajovické kopce; Onopordon acanthium", "Dunajovické kopce"],
 macedonia_2019: ["", "NP Fruška Gora", "", "Nemoptera sinuata, stuholetka jižní", "kaňon Matka", "kaňon Matka", "kaňon Matka", "kaňon Matka", "Popova Shapka", "Popova Shapka", "Carex caryophyllea", "Popova Shapka", "", "Lilium albanicum", "Saxifraga sempervivum", "Popova Shapka", "Crocus scardicus", "Popova Shapka", "Popova Shapka", "", "Mavrovo", "Mavrovo", "Mavrovo", "Krani", "Krani", "NP Galičica", "NP Galičica", "NP Galičica", "NP Galičica, Dactylorhiza sambucina", "NP Galičica", "NP Galičica", "", "NP Pelister", "NP Pelister", "Demir Kapija", "Demir Kapija", "Centaurea sp.", "Demir Kapija", "Demir Kapija", "Ovče Pole", "Ovče Pole", "Ovče Pole", "Peganum harmala", ],
  corsica_2018: ["", "", "Ponte Novo", "Ponte Novo", "Monte Cintu, Calacuccia", "Monte Cintu, Daphne oleoides", "Monte Cintu, Heleborus lividus", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio",  "", "", "", "", "", "", "Étang de Biguglia", "Étang de Biguglia", "Étang de Biguglia", "" ],
  romania_2017: ["Rodna, Manastrirea Sfanta Treime", "Rodna","Rodna","Rodna","Rodna", "Rodna, Stiol lake", "Rodna, Stiol lake","Rodna","Ceahlau", "Ceahlau, Cușma Dorobanțului",  "Ceahlau", "Ceahlau", "Lathyrus laevigatus", "Ceahlau", "Ceahlau", "Ceahlau", "Voslabeni", "Bucin", "Muntele de Sare", "Muntele de Sare", "Sovata", "Vlahita", "Vlahita", "Vlahita", "Lacul Sfanta Ana", "Salamandra salamandra", "Cheile Rasnoavei", "Cheile Rasnoavei", "Saline Turda", "Saline Turda", "Saline Turda", "Fanatele Clujului, Clematis integrifolia", "Fanatele Clujului", "Fanatele Clujului, Carex secalina", "Fanatele Clujului","Cheile Turzii", "Cheile Turzii", "Cheile Turzii", "Rachitele", "Rachitele"],
  albania_2016: ["Anacamptis pyramidalis", "přástevník Epicallia villica", "", "", "", "Clathrus ruber, mřížovka červená", "", "", "", "", "Eleocharis sp.", "", "Echium maculatum", "Euphorbia spinosa", "", "", "", "", "", "", "Narcissus poeticus",  "", "", "", "Daphne blagayana", "Erythronium dens-canis", "", "", ],
  serbia_2015: ["", "", "", "", "Sahara", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",  "", "Orchis coriophora", "", "", "", ],
  poland_2014: ["", "", "Echium russicum", "", "", "", "", "", "", "", "", "", "", "", "hadovka smrdutá", "", "", "", "bekyně velkohlavá", "Agrostemma githago", "", "", "", "", "", "",  "", "Viola tricolor subsp. subalpina", "Bielzia coerulans, modranka karpatská",],
  sardinia_2013: ["01", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",  "", "", "", "", "", ],
  swiss_2012: ["01", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ],
  turkey_2011: ["01", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ],
  
  italy_2007: ["Amelanchier ovalis", "Bougenvillea speciosa", "Calystegia soldanella", "Doronicum columnae", "Eryngium maritimum", "Hesperis laciniata", "", "", "", "", "", "", "", "", "", "", "Calystegia soldanella", "", "Punica granatum", "Sedum hispanicum"],
  
};

export const galleryLabelsEn = {
  austria_2021: ["", "Neusiedler See", "Hordeum jubatum", "Erigeron podolicus", "Neusiedler See", "Neusiedler See", "Allium angulosum", "Neusiedler See", "Neusiedl am See, Kalvarienberg", "Neusiedl am See, Kalvarienberg", "Koralpen", "Gentiana pannonica", "Koralpen", "Koralpen", "Dianthus superbus", "Koralpen", "Koralpen, Grosser Speikkogel", "", "Faaker See", "Faaker See", "Faaker See", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Lienzer Dolomiten, Lasersee", "Dryas octopetala", "Lienzer Dolomiten, Lasersee", "Pasterze", "Pasterze", "Cirsium spinosissimum", "Marmota marmota", "Leontopodium alpinum", "Sempervivum arachnoideum", "Lomatogonium carinthiacum", "", "Warscheneck", "Wienerwald, Pinus nigra"],
  jeseniky_2021: ["Velký kotel", "", "", "Trollius altissimus", "", "", "", "Plantago atrata", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "Vysoká hole", "", "", "", "Listera cordata", "", "", "", "Salix herbacea", "", "Poa riphaea", "", "", "", "", ],
  slovakia_2020: ["", "Terchová-Diery", "Corthusa matthioli", "Terchová-Diery","", "Cirsium eriophorum", "Terchová-Tiesňavy", "Ranunculus alpestris", "V. Fatra-Tlstá", "Gentianella sp.", "V. Fatra-Tlstá", "Lappula squarrosa", "Velká Fatra", "Velká Fatra", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Malá Studená dolina", "Rhodiola rosea", "Gentiana asclepiadea", "Adenostyles alliariae", "Malá Studená dolina", "Spišské pleso", "Spišské pleso","Salix herbacea", "Téryho chata", "kemp Tatranská Štrba", "kemp Tatranská Štrba", "kemp Tatranská Štrba; výstavka","Primovské skaly", "Primovské skaly", "Galatella linosyris", "Eresus kollari", "Sivá brada", "Sivá brada", "Sivá brada", "Sivá brada", "Ostrá hora", "Ostrá hora", "Aconitum anthora", "Velké Biele pleso", "Kopské sedlo", "Kopské sedlo", "Kopské sedlo", "Adenophora liliifolia", "Rosa pendulina", "Rosa spinosissima", "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Prielom Hornádu" , "Geastrum sp.", "Prielom Hornádu" , "Stratenský kaňon", "Hnilecká jelšina", "Succisa pratensis + Polygonia c-album", "Ligularia sibirica", "Hnilecká jelšina", "Hnilecká jelšina", "Coronabus :-)"],
  slaniska_2020: ["Trifolium fragiferum", "Lotus tenuis", "Sedlec", "", "", "","Slanisko u Nesytu", "Slanisko u Nesytu", "Slanisko u Nesytu", "Slanisko u Nesytu", "Dolní Dunajovice", "Dolní Dunajovice", "Zwingendorf", "Zwingendorf", "Zwingendorf", "Zwingendorf", "Zwingendorf; Althaea officinalis", "Zwingendorf", "Zwingendorf", "Nový Přerov", "Nový Přerov", "Nový Přerov", "Nový Přerov", "Starovický rybník", "Trkmanec-Rybníčky", "Trkmanec-Rybníčky", "Trkmanec-Rybníčky", "Dobré Pole", "Novosedly", "", "", "", "Dunajovické kopce; Crambe tataria", "Dunajovické kopce","Dunajovické kopce; Linum hirsutum", "Dunajovické kopce; Onopordon acanthium", "Dunajovické kopce"],
 macedonia_2019: ["", "NP Fruška Gora", "", "Nemoptera sinuata, stuholetka jižní", "kaňon Matka", "kaňon Matka", "kaňon Matka", "kaňon Matka", "Popova Shapka", "Popova Shapka", "Carex caryophyllea", "Popova Shapka", "", "Lilium albanicum", "Saxifraga sempervivum", "Popova Shapka", "Crocus scardicus", "Popova Shapka", "Popova Shapka", "", "Mavrovo", "Mavrovo", "Mavrovo", "Krani", "Krani", "NP Galičica", "NP Galičica", "NP Galičica", "NP Galičica, Dactylorhiza sambucina", "NP Galičica", "NP Galičica", "", "NP Pelister", "NP Pelister", "Demir Kapija", "Demir Kapija", "Centaurea sp.", "Demir Kapija", "Demir Kapija", "Ovče Pole", "Ovče Pole", "Ovče Pole", "Peganum harmala", ],
  corsica_2018: ["", "", "Ponte Novo", "Ponte Novo", "Monte Cintu, Calacuccia", "Monte Cintu, Daphne oleoides", "Monte Cintu, Heleborus lividus", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "Lac de Nino", "", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio", "Bonifacio",  "", "", "", "", "", "", "Étang de Biguglia", "Étang de Biguglia", "Étang de Biguglia", "" ],
  romania_2017: ["Rodna, Manastrirea Sfanta Treime", "Rodna","Rodna","Rodna","Rodna", "Rodna, Stiol lake", "Rodna, Stiol lake","Rodna","Ceahlau", "Ceahlau, Cușma Dorobanțului",  "Ceahlau", "Ceahlau", "Lathyrus laevigatus", "Ceahlau", "Ceahlau", "Ceahlau", "Voslabeni", "Bucin", "Muntele de Sare", "Muntele de Sare", "Sovata", "Vlahita", "Vlahita", "Vlahita", "Lacul Sfanta Ana", "Salamandra salamandra", "Cheile Rasnoavei", "Cheile Rasnoavei", "Saline Turda", "Saline Turda", "Saline Turda", "Fanatele Clujului, Clematis integrifolia", "Fanatele Clujului", "Fanatele Clujului, Carex secalina", "Fanatele Clujului","Cheile Turzii", "Cheile Turzii", "Cheile Turzii", "Rachitele", "Rachitele"],
  albania_2016: ["Anacamptis pyramidalis", "přástevník Epicallia villica", "", "", "", "Clathrus ruber, mřížovka červená", "", "", "", "", "Eleocharis sp.", "", "Echium maculatum", "Euphorbia spinosa", "", "", "", "", "", "", "Narcissus poeticus",  "", "", "", "Daphne blagayana", "Erythronium dens-canis", "", "", ],
  serbia_2015: ["", "", "", "", "Sahara", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",  "", "Orchis coriophora", "", "", "", ],
  poland_2014: ["", "", "Echium russicum", "", "", "", "", "", "", "", "", "", "", "", "hadovka smrdutá", "", "", "", "bekyně velkohlavá", "Agrostemma githago", "", "", "", "", "", "",  "", "Viola tricolor subsp. subalpina", "Bielzia coerulans, modranka karpatská",],
};
